### ISSUE TITLE
Add new partners from ACI to 'Grid Use Cases' on .io

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/data_partners#20]
- Covid Fighters
- Green Edge
- Zetako
- Crystal Twin
- Crystal Home
- Earth Project
- Generation Blue
- Money of Good
- Vlinder 

See - https://staging.consciousinternet.org/#/projects for info 

I will add information to wiki.threefold.io in partner section.

**Comment by Sacha96** [comment]
link to ACI pages for partners 

- Example for Covid Fighters like to https://www.consciousinternet.org/#/projects/CovidFighters

Can see all projects here - https://www.consciousinternet.org/#/projects

**Comment by ehab-hassan** [comment]
done

**Comment by Sacha96** [comment]
@ehab-hassan if you can set up this last one then we can push to done 

- https://www.consciousinternet.org/#/projects/Crystal%20Programming%20Language

Name: Crystal Language
Description: *Take 'About' section from ACI - copy paste into >>> data_partners
Order: doesn't matter for now

**Comment by ehab-hassan** [comment]
Crystal Language added

**Comment by sasha-astiadi** [comment]
lets clean up. what is the status now? project is expired already.
