### ISSUE TITLE
Add new partners to 'Blockchain Partners'

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/data_partners#21]
- Dash
- WaykiChain (logo already in files)
- SkaleLabs 

Logo

Dash: https://www.dash.org/brand-assets/ 

SkaleLabs: https://images.prismic.io/skalelabs/eb94376c-4e95-4a9b-9999-bdf00cb8f053_Skale_Logo_Black.png?auto=compress,format

**Comment by ehab-hassan** [comment]
done

**Comment by Sacha96** [comment]
reopening for stakeholder review only
